"""add run_id to deal_matches

Revision ID: 0ce68cc5557c
Revises: 971d327f1066
Create Date: 2026-01-22 02:22:21.035808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce68cc5557c'
down_revision: Union[str, None] = '971d327f1066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_matches', sa.Column('run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deal_matches_run_id'), 'deal_matches', ['run_id'], unique=False)
    op.create_foreign_key(None, 'deal_matches', 'signal_runs', ['run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal_matches', type_='foreignkey')
    op.drop_index(op.f('ix_deal_matches_run_id'), table_name='deal_matches')
    op.drop_column('deal_matches', 'run_id')
    # ### end Alembic commands ###
