"""add signal_runs and deal_matches.run_id

Revision ID: 8a29364bcc68
Revises: a15370286d0d
Create Date: 2026-01-22 02:12:54.783447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a29364bcc68'
down_revision: Union[str, None] = 'a15370286d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Enum('morning', 'afternoon', 'manual', 'test', name='signal_run_type'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='signal_run_status'), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('matches_created_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_runs_signal_id'), 'signal_runs', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_runs_started_at'), 'signal_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_signal_runs_status'), 'signal_runs', ['status'], unique=False)
    op.drop_index('ix_deal_matches_signal_id_matched_at', table_name='deal_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_deal_matches_signal_id_matched_at', 'deal_matches', ['signal_id', sa.text('matched_at DESC')], unique=False)
    op.drop_index(op.f('ix_signal_runs_status'), table_name='signal_runs')
    op.drop_index(op.f('ix_signal_runs_started_at'), table_name='signal_runs')
    op.drop_index(op.f('ix_signal_runs_signal_id'), table_name='signal_runs')
    op.drop_table('signal_runs')
    # ### end Alembic commands ###
