"""add deals and deal_matches

Revision ID: a15370286d0d
Revises: 7cf8bd12c66b
Create Date: 2026-01-21 03:13:39.775936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15370286d0d'
down_revision: Union[str, None] = '7cf8bd12c66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deal_matches_deal_id_fkey', 'deal_matches', type_='foreignkey')
    op.drop_constraint('deal_matches_signal_id_fkey', 'deal_matches', type_='foreignkey')
    op.create_foreign_key(None, 'deal_matches', 'signals', ['signal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deal_matches', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal_matches', type_='foreignkey')
    op.drop_constraint(None, 'deal_matches', type_='foreignkey')
    op.create_foreign_key('deal_matches_signal_id_fkey', 'deal_matches', 'signals', ['signal_id'], ['id'])
    op.create_foreign_key('deal_matches_deal_id_fkey', 'deal_matches', 'deals', ['deal_id'], ['id'])
    # ### end Alembic commands ###
